### ISSUE TITLE
ecs: logging is somewhat broken; also, outdated options

### ISSUE THREAD

**Issue by vthriller** [processone/docker-ejabberd#53] opened 2020-02-14 13:59 UTC
Minimal example (stock config etc):

```
# docker run --name ejabberd ejabberd/ecs:20.01
2020-02-14 13:48:22.695432+00:00 [critical] Failed to set logging: {error,
                           {handler_not_added,
                               {invalid_config,logger_std_h,
                                   #{file =>
                                         "/home/ejabberd/logs/ejabberd.log"}}}}
2020-02-14 13:48:23.005695+00:00 [warning] Option 'log_rotate_date' is deprecated and has no effect anymore. Please remove it from the configuration.
2020-02-14 13:48:23.005974+00:00 [warning] Option 'log_rate_limit' is deprecated and has no effect anymore. Please remove it from the configuration.
…
```

It still logs to stdout/stderr, however snippet from image's README does not work:

```
# docker exec -it ejabberd tail -f logs/ejabberd.log
tail: can't open 'logs/ejabberd.log': No such file or directory
tail: no files
```

So there's two ways to resolve this:

- fix the file logging,
- embrace std streams for logging and update README accordingly.

**Comment by mremond** [comment] 2020-02-18 09:42
The problem is with the Erlang version packaged with that Alpine release.

We are going package a new image with a newer Alpine that solves the issue.

Thanks for reporting this.

**Comment by mremond** [comment] 2020-02-18 09:44
Fixed in https://github.com/processone/docker-ejabberd/commit/72d3b25a0f9f8e5580b75c09929ce983d3a718aa

**Closed by mremond** 2020-02-18 09:44 UTC
