### ISSUE TITLE
** (Mix) Unknown package ex_doc in lockfile

### ISSUE THREAD

**Issue by vnthanhdv** [processone/docker-ejabberd#52] opened 2020-02-05 04:32 UTC
I build and get thr error:

** (Mix) Unknown package ex_doc in lockfile
The command '/bin/sh -c git checkout ${VERSION/latest/HEAD}  && mix deps.get  && (cd deps/eimp; ./configure)' returned a non-zero code: 1

Please help me check and resolve

**Comment by mremond** [comment] 2020-02-26 13:33
We need more details ?
How do you build ? Which commands did you type ?

Thanks!

**Comment by mremond** [comment] 2020-03-31 14:36
Closing, as I cannot reproduce the issue.

**Closed by mremond** 2020-03-31 14:36 UTC
