### ISSUE TITLE
`go.mod:3: invalid go version '1.21.3': must match format 1.23`

### ISSUE THREAD

**Issue by paulmenzel** [processone/docker-ejabberd#115] opened 2024-06-08 12:33 UTC
https://github.com/processone/docker-ejabberd/blob/ce8ea0a59fdacc4169a9e9531e56d06ac733982f/ecs/Dockerfile#L1

Lately, this results in:

    $ ./build.sh latest
    Sending build context to Docker daemon  83.46kB
    Step 1/35 : FROM docker.io/golang:1.20-alpine AS api
     ---> 71719a2da3d1
    Step 2/35 : RUN go install -v     github.com/processone/ejabberd-api/cmd/ejabberd@master     && mv bin/ejabberd bin/ejabberdapi
     ---> Running in 0870c58d9b44
    go: downloading github.com/processone/ejabberd-api v0.0.0-20240607151029-3a5c8e3fc4ef
    go: github.com/processone/ejabberd-api/cmd/ejabberd@master (in github.com/processone/ejabberd-api@v0.0.0-20240607151029-3a5c8e3fc4ef): go.mod:3: invalid go version '1.21.3': must match format 1.23

**Comment by badlop** [comment] 2024-06-13 13:43
Aha, this was caused by https://github.com/processone/ejabberd-api/commit/3a5c8e3fc4efe799a409433babb27f5bbc466d6c

I hope it's fixed now in ejabberd-api, and also this Dockerfile apparently required a change to get latest code.

Can you try again?

**Closed** 2024-06-13 14:19 UTC
